### ISSUE TITLE
Error in Dockerfile

### ISSUE THREAD

**Issue by rschwend** [mawinkler/playground-one#1]
Error:
`docker build .
[+] Building 1.2s (10/16)                                                                                                                                                        docker:desktop-linux
 => [internal] load build definition from Dockerfile                                                                                                                                             0.0s
 => => transferring dockerfile: 2.51kB                                                                                                                                                           0.0s
 => [internal] load metadata for docker.io/library/ubuntu:22.04                                                                                                                                  1.0s
 => [auth] library/ubuntu:pull token for registry-1.docker.io                                                                                                                                    0.0s
 => [internal] load .dockerignore                                                                                                                                                                0.0s
 => => transferring context: 2B                                                                                                                                                                  0.0s
 => [base 1/8] FROM docker.io/library/ubuntu:22.04@sha256:a6d2b38300ce017add71440577d5b0a90460d0e57fd7aec21dd0d1b0761bbfb2                                                                       0.0s
 => CACHED [base 2/8] RUN ln -snf /usr/share/zoneinfo/${TZ} /etc/localtime && echo ${TZ} > /etc/timezone                                                                                         0.0s
 => CACHED [base 3/8] RUN addgroup -gid ${gid} pgo || true                                                                                                                                       0.0s
 => CACHED [base 4/8] RUN addgroup -gid 990 c9damzn || true                                                                                                                                      0.0s
 => CACHED [base 5/8] RUN addgroup -gid 999 c9dubuntu || true                                                                                                                                    0.0s
 => ERROR [base 6/8] RUN useradd -m -s /usr/bin/bash -d /home/pgo -u ${uid} -g ${gid} pgo &&     usermod -a -G 990 pgo &&     usermod -a -G 999 pgo                                              0.2s
------                                                                                                                                                                                                
 > [base 6/8] RUN useradd -m -s /usr/bin/bash -d /home/pgo -u ${uid} -g ${gid} pgo &&     usermod -a -G 990 pgo &&     usermod -a -G 999 pgo:
0.130 useradd: invalid user ID '-g'
------
Dockerfile:21
--------------------
  20 |     # Add user pgo and add user to group id of Cloud9 Amazon Linux docker groups
  21 | >>> RUN useradd -m -s /usr/bin/bash -d /home/${user} -u ${uid} -g ${gid} ${user} && \
  22 | >>>     usermod -a -G 990 ${user} && \
  23 | >>>     usermod -a -G 999 ${user}
  24 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c useradd -m -s /usr/bin/bash -d /home/${user} -u ${uid} -g ${gid} ${user} &&     usermod -a -G 990 ${user} &&     usermod -a -G 999 ${user}" did not complete successfully: exit code: 3

View build details: docker-desktop://dashboard/build/desktop-linux/desktop-linux/ulbnnjel7zu1poy5tn2a7j8r8`

-----------------------------------------------------------------------------------------------------------------

Fix:

`# Arguments with default values
ARG uid=1000
ARG gid=1000

# Add user and groups
RUN addgroup -gid ${gid} ${group} || true
RUN useradd -m -s /usr/bin/bash -d /home/${user} -u ${uid} -g ${gid} ${user} && \
    usermod -a -G 990 ${user} && \
    usermod -a -G 999 ${user}
`

Please update the Dockerfile.

**Comment by mawinkler** [comment]
Two questions:

- Did you use the `build.sh` or `release.sh` to build the image or did you simply use `docker build`?
- If you used one of the scripts, on which operating system are you?

**Comment by rschwend** [comment]
I have used `docker build .` in the Directory with the Dockerfile.

**Comment by mawinkler** [comment]
Sorry for late reply. This does not work that way. Check out `container/build.sh`
